import type { BadgeProps } from '../Components/Atoms/Badge';
import type { BreadcrumbsProps } from '../Components/Atoms/Breadcrumbs';
import type { ButtonProps } from '../Components/Atoms/Button';
import type { DropdownProps } from '../Components/Atoms/Dropdown';
import type { FormattedNumberProps } from '../Components/Atoms/FormattedNumber';
import type { IconProps } from '../Components/Atoms/Icon';
import type { ImageProps } from '../Components/Atoms/Image';
import type { LoadingBarProps } from '../Components/Atoms/Loading';
import type { BannerProps, InlineBannerProps } from '../Components/Atoms/Merchandising';
import type { OverlayProps } from '../Components/Atoms/Overlay';
import type { PriceProps } from '../Components/Atoms/Price';
import type { SkeletonProps } from '../Components/Atoms/Skeleton';
import type { TermsProps } from '../Components/Atoms/Terms';
import type { CarouselProps } from '../Components/Molecules/Carousel';
import type { CheckboxProps } from '../Components/Molecules/Checkbox';
import type { ErrorHandlerProps } from '../Components/Molecules/ErrorHandler';
import type { FacetGridOptionsProps } from '../Components/Molecules/FacetGridOptions';
import type { FacetHierarchyOptionsProps } from '../Components/Molecules/FacetHierarchyOptions';
import type { FacetListOptionsProps } from '../Components/Molecules/FacetListOptions';
import type { FacetPaletteOptionsProps } from '../Components/Molecules/FacetPaletteOptions';
import type { FacetSliderProps } from '../Components/Molecules/FacetSlider';
import type { FilterProps } from '../Components/Molecules/Filter';
import type { PaginationProps } from '../Components/Molecules/Pagination';
import type { PerPageProps } from '../Components/Molecules/PerPage';
import type { RatingProps } from '../Components/Molecules/Rating';
import type { ResultProps } from '../Components/Molecules/Result';
import type { SearchInputProps } from '../Components/Molecules/SearchInput';
import type { LoadMoreProps } from '../Components/Molecules/LoadMore';
import type { SelectProps } from '../Components/Molecules/Select';
import type { SlideoutProps } from '../Components/Molecules/Slideout';
import type { SortByProps } from '../Components/Molecules/SortBy';
import type { BranchOverrideProps } from '../Components/Organisms/BranchOverride';
import type { FacetProps } from '../Components/Organisms/Facet';
import type { FacetsProps } from '../Components/Organisms/Facets';
import type { FilterSummaryProps } from '../Components/Organisms/FilterSummary';
import type { ResultsProps } from '../Components/Organisms/Results';
import type { SearchHeaderProps } from '../Components/Atoms/SearchHeader';
import type { SidebarProps } from '../Components/Organisms/Sidebar';
import type { ToolbarProps } from '../Components/Organisms/Toolbar';
import type { AutocompleteProps } from '../Components/Templates/Autocomplete';
import type { RecommendationProps } from '../Components/Templates/Recommendation';
import type { SearchProps } from '../Components/Templates/Search';
import type { NoResultsProps } from '../Components/Atoms/NoResults';
import type { MobileSidebarProps } from '../Components/Organisms/MobileSidebar';
import type { FacetToggleProps } from '../Components/Molecules/FacetToggle';
import type { ToggleProps } from '../Components/Atoms/Toggle';
import type { RadioListProps } from '../Components/Molecules/RadioList';
import type { ListProps } from '../Components/Molecules/List';
import type { RadioProps } from '../Components/Molecules/Radio';
import type { LayoutSelectorProps } from '../Components/Molecules/LayoutSelector';

type GenericComponentProps<ComponentProps> = Partial<ComponentProps> & { named?: { [named: string]: Partial<ComponentProps> } };

export type ThemeComponents = {
	/* ATOMS */
	badge?: GenericComponentProps<BadgeProps>;
	breadcrumbs?: GenericComponentProps<BreadcrumbsProps>;
	button?: GenericComponentProps<ButtonProps>;
	dropdown?: GenericComponentProps<DropdownProps>;
	formattedNumber?: GenericComponentProps<FormattedNumberProps>;
	icon?: GenericComponentProps<IconProps>;
	image?: GenericComponentProps<ImageProps>;
	loadingBar?: GenericComponentProps<LoadingBarProps>;
	banner?: GenericComponentProps<BannerProps>;
	inlineBanner?: GenericComponentProps<InlineBannerProps>;
	overlay?: GenericComponentProps<OverlayProps>;
	price?: GenericComponentProps<PriceProps>;
	skeleton?: GenericComponentProps<SkeletonProps>;
	terms?: GenericComponentProps<TermsProps>;
	toggle?: GenericComponentProps<ToggleProps>;

	/* MOLECULES */
	carousel?: GenericComponentProps<CarouselProps>;
	checkbox?: GenericComponentProps<CheckboxProps>;
	radio?: GenericComponentProps<RadioProps>;
	errorHandler?: GenericComponentProps<ErrorHandlerProps>;
	facetGridOptions?: GenericComponentProps<FacetGridOptionsProps>;
	facetHierarchyOptions?: GenericComponentProps<FacetHierarchyOptionsProps>;
	facetListOptions?: GenericComponentProps<FacetListOptionsProps>;
	facetPaletteOptions?: GenericComponentProps<FacetPaletteOptionsProps>;
	facetSlider?: GenericComponentProps<FacetSliderProps>;
	filter?: GenericComponentProps<FilterProps>;
	loadMore?: GenericComponentProps<LoadMoreProps>;
	pagination?: GenericComponentProps<PaginationProps>;
	perPage?: GenericComponentProps<PerPageProps>;
	rating?: GenericComponentProps<RatingProps>;
	result?: GenericComponentProps<ResultProps>;
	searchInput?: GenericComponentProps<SearchInputProps>;
	select?: GenericComponentProps<SelectProps>;
	slideout?: GenericComponentProps<SlideoutProps>;
	sortBy?: GenericComponentProps<SortByProps>;
	facetToggle?: GenericComponentProps<FacetToggleProps>;
	radioList?: GenericComponentProps<RadioListProps>;
	list?: GenericComponentProps<ListProps>;
	layoutSelector?: GenericComponentProps<LayoutSelectorProps>;

	/* ORGANISMS */
	branchOverride?: GenericComponentProps<BranchOverrideProps>;
	facet?: GenericComponentProps<FacetProps>;
	facets?: GenericComponentProps<FacetsProps>;
	filterSummary?: GenericComponentProps<FilterSummaryProps>;
	noResults?: GenericComponentProps<NoResultsProps>;
	results?: GenericComponentProps<ResultsProps>;
	searchHeader?: GenericComponentProps<SearchHeaderProps>;
	sidebar?: GenericComponentProps<SidebarProps>;
	mobileSidebar?: GenericComponentProps<MobileSidebarProps>;
	toolbar?: GenericComponentProps<ToolbarProps>;
	/* TEMPLATES */
	autocomplete?: GenericComponentProps<AutocompleteProps>;
	recommendation?: GenericComponentProps<RecommendationProps>;
	search?: GenericComponentProps<SearchProps>;
};
