name: Docs

on:
  workflow_run:
    workflows: ["Publish"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repositiory
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          ref: "docs"

      - name: Set Github credentials
        run: |
          git config user.name searchspring-machine
          git config user.email machine@searchspring.com

      - name: Merge main into docs branch
        run: |
          git merge origin/main

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: 'https://npm.pkg.github.com'
          scope: '@searchspring'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
      
      - name: Build
        run: | 
          npm run build

      - name: Build docs
        run: |
          npm run build:docs 
          git add -A packages/snap-*/docs/ 
          git commit -m "chore(docs): generation"
          git push
