name: Patch Generate

on:
  workflow_run:
    workflows: ["Publish"]
    types: [completed]
    branches: [main]

jobs:
  PatchGenerate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        framework: [preact]
    steps:
      - name: Checkout Snap repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout snapfu-library repository
        uses: actions/checkout@v3
        with:
          repository: "athoscommerce/snapfu-library"
          path: "snapfu-library"
          ref: "main"
          token: ${{ secrets.MACHINE_ACTION_WORKFLOW_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Determine version
        run: |
          echo "version=$(jq -r .version < lerna.json)" >> $GITHUB_ENV

      - name: Generate ${{ matrix.framework }} patch file
        run: |
          node .github/workflows/scripts/generatePatchFile.js --version ${{ env.version }} --framework ${{ matrix.framework }}
          mkdir -p snapfu-library/searchspring/${{ matrix.framework }}/patches/${{ env.version }}
          cp patch.${{ matrix.framework }}.${{ env.version }}.yml snapfu-library/searchspring/${{ matrix.framework }}/patches/${{ env.version }}/

      - name: Commit patch files
        working-directory: snapfu-library
        run: |
          git config --global user.name "searchspring-machine"
          git config --global user.email "machine@searchspring.com"
          git checkout -b patch-generate-searchspring-${{ matrix.framework }}-${{ env.version }}
          git add .
          git commit -m "auto generated patch files from 'Patch Generate' action workflow"
          git push -u origin patch-generate-searchspring-${{ matrix.framework }}-${{ env.version }}

      - name: Create PR
        run: |
          gh pr create --title "Patch file searchspring/${{ matrix.framework }}/${{ env.version }}" --body "" --repo "https://github.com/athoscommerce/snapfu-library" --base "main" --head "patch-generate-searchspring-${{ matrix.framework }}-${{ env.version }}" --reviewer "athoscommerce/snap-team"
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_ACTION_WORKFLOW_PAT }}
